pruebasunitarias_ = Array(
    // analysis_preparation
    //id_analysys_prepraration
    Array(1, "analysis_preparation", "id_analysis_preparation", 1, "", false),
    Array(1, "analysis_preparation", "id_analysis_preparation", 2, "123456", true),
    Array(2, "analysis_preparation", "id_analysis_preparation", 3, "12345678901245", false),
    Array(2, "analysis_preparation", "id_analysis_preparation", 4, "12345678", true),
    Array(3, "analysis_preparation", "id_analysis_preparation", 5, "hola", false),
    Array(3, "analysis_preparation", "id_analysis_preparation", 6, "45698bca", false),
    Array(3, "analysis_preparation", "id_analysis_preparation", 7, "7894", false),
    Array(3, "analysis_preparation", "id_analysis_preparation", 8, "789465", true),
    Array(4, "analysis_preparation", "id_analysis preparation", 9, "a021123", false),
    Array(4, "analysis_preparation", "id_analysis_preparation", 10, "123456789", true),
    //name_analysis_preparation
    Array(5, "analysis_preparation", "name_analysis_preparation", 11, "hola", false),
    Array(5, "analysis_preparation", "name_analysis_preparation", 12, "objetivo", true),
    Array(6, "analysis_preparation", "name_analysis_preparation", 13, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean a accumsan tortor. Vestibulum velit.a", false),
    Array(6, "analysis_preparation", "name_analysis_preparation", 14, "Nombre del analisis a realizar", true),
    Array(7, "analysis_preparation", "name_analysis_preparation", 15, "nombre de analisis con ñ", false),
    Array(7, "analysis_preparation", "name_analysis_preparation", 16, "nombre de analisis con un acento á", false),
    Array(7, "analysis_preparation", "name_analysis_preparation", 17, "nombre de analisis con un acento ù", false),
    Array(7, "analysis_preparation", "name_analysis_preparation", 18, "nombre de analisis con un acento û", false),
    Array(7, "analysis_preparation", "name_analysis_preparation", 19, "nombre de analisis con un acento ñ y acentos", false),
    Array(7, "analysis_preparation", "name_analysis_preparation", 20, "nombre de analisis correcto", true),
    Array(8, "analysis_preparation", "name_analysis_preparation", 21, "24762356", false),
    Array(8, "analysis_preparation", "name_analysis_preparation", 22, "un nombre de analisis correcto", true),
    //description_analysis_preparation 
    Array(9, "analysis_preparation", "description_analysis_preparation", 23, "hola".repeat(10), false),
    Array(9, "analysis_preparation", "description_analysis_preparation", 24, "hola".repeat(30), true),
    Array(10, "analysis_preparation", "description_analysis_preparation", 25, "hola".repeat(2000) ,false),
    Array(10, "analysis_preparation", "description_analysis_preparation", 26, "hola".repeat(1000), true),
    Array(11, "analysis_preparation", "description_analysis_preparation", 27, "descripcion de proyecto con ñ porque la ñ es una letra simbolo de nuestro maravilloso idioma el castellano", false),
    Array(11, "analysis_preparation", "description_analysis_preparation", 28, "descripcion de proyecto con un acento á porque para algo existirán las tildes ademas de tocar las narices", false),
    Array(11, "analysis_preparation", "description_analysis_preparation", 29, "descripcion de proyecto con un acento ù porque para algo existirán las tildes ademas de tocar las narices", false),
    Array(11, "analysis_preparation", "description_analysis_preparation", 30, "descripcion de proyecto con un acento û porque para algo existirán las tildes ademas de tocar las narices", false),
    Array(11, "analysis_preparation", "description_analysis_preparation", 31, "descripcion de proyecto con un acento ñ y acentos porque para algo existirán los acentos ademas de tocar las narices", false),
    Array(11, "analysis_preparation", "description_analysis_preparation", 32, "descripcion de proyecto correcto sin caracteres innecesarios ni acentos ni letras que no formen de los caracteres indefinidos", true),
    Array(12, "analysis_preparation", "description_analysis_preparation", 33, "24762356erfhgtoiujhyhtgrfexdaezrydxftcuvyubhgiohbñv ilcukx456841465rgtdygfc4g5gfd5f11gf45hg8h87rt4h5ghf54h8tr4hg2f1vr842vfd", false),
    Array(12, "analysis_preparation", "description_analysis_preparation", 34, "una descripcion de analisis correcto sin acentos ni caracateres incorrectos que causen problemas", true),
    //bib_analysys_preparation
    Array(13, "analysis_preparation", "bib_analysis_preparation", 35, "hola", false),
    Array(13, "analysis_preparation", "bib_analysis_preparation", 36, "objetivo", true),
    Array(14, "analysis_preparation", "bib_analysis_preparation", 37, "un elemento normal".repeat(20), false),
    Array(14, "analysis_preparation", "bib_analysis_preparation", 38, "no se me ocurre nada para poner aquí", true),
    Array(15, "analysis_preparation", "bib_analysis_preparation", 39, "no se me ocurre nada para poner aquí -3-", false),
    Array(15, "analysis_preparation", "bib_analysis_preparation", 40, "otra frase en la que digo que no se me ocurre nada", true),
    Array(16, "analysis_preparation", "bib_analysis_preparation", 41, "24762356", false),
    Array(16, "analysis_preparation", "bib_analysis_preparation", 42, "Otro test correcto, otros cientos que elaborar", true),
    //file_analysys_preparation
    Array(17, "analysis_preparation", "file_analysis_preparation", 43, "hola", false),
    Array(17, "analysis_preparation", "file_analysis_preparation", 44, "holasoyunpdf", false),
    Array(18, "analysis_preparation", "file_analysis_preparation", 45, "soyundocx".repeat(15), false),
    Array(18, "analysis_preparation", "file_analysis_preparation", 46, "holasoyundocumentodetexto", true),
    Array(19, "analysis_preparation", "file_analysis_preparation", 47, "soyunpdfconñ", false),
    Array(19, "analysis_preparation", "file_analysis_preparation", 48, "hola tengo espacios", false),
    Array(19, "analysis_preparation", "file_analysis_preparation", 49, "holatengounacentoá", false),
    Array(19, "analysis_preparation", "file_analysis_preparation", 50, "soy un pdf con espacios y con símbolos porhibidos", false),
    Array(19, "analysis_preparation", "file_analysis_preparation", 51, "soy un doxc con exclamaciones! (y espacios)", false),
    Array(19, "analysis_preparation", "file_analysis_preparation", 52, "soyundocumentoquecumpletodaslasreglas", true),
    Array(20, "analysis_preparation", "file_analysis_preparation", 53, "5429sfdrtgryhyjuk", false),
    Array(20, "analysis_preparation", "file_analysis_preparation", 54, "soyundocumentoquecumpletodaslasreglasuwu", true),
    //project
    //id_project
    Array(21, "project", "id_project", 55, "", false),
    Array(21, "project", "id_project", 56, "123456", true),
    Array(22, "project", "id_project", 57, "12345678901245", false),
    Array(22, "project", "id_project", 58, "12345678", true),
    Array(23, "project", "id_project", 59, "hola", false),
    Array(23, "project", "id_project", 60, "45698bca", false),
    Array(23, "project", "id_project", 61, "7894", false),
    Array(23, "project", "id_project", 62, "789465", true),
    Array(24, "project", "id_project", 63, "24987a78", false),
    Array(24, "project", "id_project", 64, "123456789", true),
    //name_project
    Array(25, "project", "name_project", 65, "hallo", false),
    Array(25, "project", "name_project", 66, "objetivo", true),
    Array(26, "project", "name_project", 67, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean a accumsan tortor. Vestibulum velit.a", false),
    Array(26, "project", "name_project", 68, "Nombre del proyecto a realizar", true),
    Array(27, "project", "name_project", 69, "nombre de proyecto con ñ", false),
    Array(27, "project", "name_project", 70, "nombre de proyecto con un acento á", false),
    Array(27, "project", "name_project", 71, "nombre de proyecto con un acento ù", false),
    Array(27, "project", "name_project", 72, "nombre de proyecto con un acento û", false),
    Array(27, "project", "name_project", 73, "nombre de proyecto con un acento ñ y acentos", false),
    Array(27, "project", "name_project", 74, "nombre de proyecto correcto", true),
    Array(28, "project", "name_project", 75, "24762356", false),
    Array(28, "project", "name_project", 76, "un nombre de proyecto correcto", true),
    //start_date_project
    Array(29, "project", "start_date_project", 77, "10/20/2024", false),
    Array(29, "project", "start_date_project", 78, "25-02-2025", false),
    Array(29, "project", "start_date_project", 79, "31.2.1965", false),
    Array(29, "project", "start_date_project", 80, "09.21.1965", false),
    Array(29, "project", "start_date_project", 81, "2024/10/17", false),
    Array(29, "project", "start_date_project", 82, "25/02/2025", true),
    Array(30, "project", "start_date_project", 83, "42/01/2025", false),
    Array(30, "project", "start_date_project", 84, "29/02/2025", false),
    Array(30, "project", "start_date_project", 85, "31/12/2024", true),
    Array(31, "project", "start_date_project", 86, "29/02/2025", false),
    Array(31, "project", "start_date_project", 87, "31/12/2024", true),
    //end_date_project
    Array(32, "project", "end_date_project", 88, "10/20/2024", false),
    Array(32, "project", "end_date_project", 89, "25-02-2025", false),
    Array(32, "project", "end_date_project", 90, "31.2.1965", false),
    Array(32, "project", "end_date_project", 91, "09.21.1965", false),
    Array(32, "project", "end_date_project", 92, "2024/10/17", false),
    Array(32, "project", "end_date_project", 93, "25/02/2025", true),
    Array(33, "project", "end_date_project", 94, "42/01/2025", false),
    Array(33, "project", "end_date_project", 95, "29/02/2025", false),
    Array(33, "project", "end_date_project", 96, "31/12/2024", true),
    Array(34, "project", "end_date_project", 97, "29/02/2025", false),
    Array(34, "project", "end_date_project", 98, "31/12/2024", true),
    //responsable_project
    Array(35, "project", "responsable_project", 99, "ciao", false),
    Array(35, "project", "responsable_project", 100, "objetivo", true),
    Array(36, "project", "responsable_project", 101, "un elemento normal ".repeat(5), false),  //max 60
    Array(36, "project", "responsable_project", 102, "no se me ocurre nada para poner aquí", true),
    Array(37, "project", "responsable_project", 103, "no se me ocurre nada para poner aquí -3-", false),
    Array(37, "project", "responsable_project", 104, "24h para la entrega de la ET1", false),
    Array(37, "project", "responsable_project", 105, "signos de puntuación, acentos, espacios y la letra ñ", false),
    Array(37, "project", "responsable_project", 106, "otra frase en la que digo que no se me ocurre nada", true),
    Array(38, "project", "responsable_project", 107, "24762356", false),
    Array(38, "project", "responsable_project", 108, "Otro test correcto, otros cientos que elaborar", true),
    //organization_project
    Array(39, "project", "organization_project", 109, "hawwo", false),
    Array(39, "project", "organization_project", 110, "objetivo", true),
    Array(40, "project", "organization_project", 111, "un elemento normal".repeat(20), false),  //max 100
    Array(40, "project", "organization_project", 112, "no se me ocurre nada para poner aquí", true),
    Array(41, "project", "organization_project", 113, "no se me ocurre nada para poner aquí -3-", false),
    Array(41, "project", "organization_project", 114, "24h para la entrega de la ET1", false),
    Array(41, "project", "organization_project", 115, "signos de puntuación, acentos, espacios y la letra ñ", false),
    Array(41, "project", "organization_project", 116, "otra frase en la que digo que no se me ocurre nada", true),
    Array(42, "project", "organization_project", 117, "24762356", false),
    Array(42, "project", "organization_project", 118, "Otro test correcto, otros cientos que elaborar", true),    
    //description_project
    Array(43, "project", "description_project", 119, "hawwo", false),
    Array(43, "project", "description_project", 120, "objetivo", true),
    Array(44, "project", "description_project", 121, "un elemento normal".repeat(20), false),  //max 100
    Array(44, "project", "description_project", 122, "no se me ocurre nada para poner aquí", true),
    Array(45, "project", "description_project", 123, "ねえねえねえあなたと私でランデブー？", false),
    Array(45, "project", "description_project", 124, "otra frase en la que digo que no se me ocurre nada", true),
    Array(46, "project", "description_project", 125, "24762356", false),
    Array(46, "project", "description_project", 126, "Otro test correcto, otros cientos que elaborar", true),    
    //file_project
    Array(47, "project", "file_project", 127, "hola", false),
    Array(47, "project", "file_project", 128, "holasoyunpdf", false),
    Array(48, "project", "file_project", 129, "soyundocx".repeat(15), false),
    Array(48, "project", "file_project", 130, "holasoyundocumentodetexto", true),
    Array(49, "project", "file_project", 131, "soyunpdfconñ", false),
    Array(49, "project", "file_project", 132, "hola tengo espacios", false),
    Array(49, "project", "file_project", 133, "holatengounacentoá", false),
    Array(49, "project", "file_project", 134, "soy un pdf con espacios y con símbolos porhibidos", false),
    Array(49, "project", "file_project", 135, "soy un doxc con exclamaciones! (y espacios)", false),
    Array(49, "project", "file_project", 136, "soyundocumentoquecumpletodaslasreglas", true),
    Array(50, "project", "file_project", 137, "5429sfdrtgryhyjuk", false),
    Array(50, "project", "file_project", 138, "soyundocumentoquecumpletodaslasreglasuwu", true),
    //code_project
    Array(51, "project", "code_project", 139, "hola", false),
    Array(51, "project", "code_project", 140, "holasoyuncodigo", false),
    Array(52, "project", "code_project", 141, "soyuncodigo".repeat(15), false),
    Array(52, "project", "code_project", 142, "hola soy un codigo", true),
    Array(53, "project", "code_project", 143, "soy un código con acentos", false),
    Array(53, "project", "code_project", 144, "soy un codigo sin acentos", true),
    Array(54, "project", "code_project", 145, "5429sfdrtgryhyjuk", false),
    Array(54, "project", "code_project", 146, "soy un codigo amigable uwu", true),
    //acronym_project
    Array(55, "project", "acronym_project", 147, "hola", false),
    Array(55, "project", "acronym_project", 148, "acronimo", false),
    Array(56, "project", "acronym_project", 149, "supercalifragilisticoespialidoso", false),
    Array(56, "project", "acronym_project", 150, "univuvigo", true),
    Array(57, "project", "acronym_project", 151, "univ vigo", false),
    Array(57, "project", "acronym_project", 152, "amígdala", false),
    Array(57, "project", "acronym_project", 153, "univdevigo", true),
    Array(58, "project", "acronym_project", 154, "abc1234", false),
    Array(58, "project", "acronym_project", 155, "1234568", false),
    Array(58, "project", "acronym_project", 156, "universodevigo", true),
    //id_sampling_methodology
    Array(59, "project", "id_sampling_methodology", 157, "", false),
    Array(59, "project", "id_sampling_methodology", 158, "123456", true),
    Array(60, "project", "id_sampling_methodology", 159, "12345678901245", false),
    Array(60, "project", "id_sampling_methodology", 160, "12345678", true),
    Array(61, "project", "id_sampling_methodology", 161, "hola", false),
    Array(61, "project", "id_sampling_methodology", 162, "45698bca", false),
    Array(61, "project", "id_sampling_methodology", 163, "7894", false),
    Array(61, "project", "id_sampling_methodology", 164, "789465", true),
    Array(62, "project", "id_sampling_methodology", 165, "24987a78", false),
    Array(62, "project", "id_sampling_methodology", 166, "123456789", true),
)